name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: safetyuser
          POSTGRES_PASSWORD: safepassword
          POSTGRES_DB: safetyapp
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: safetyapp
      DB_USER: safetyuser
      DB_PASSWORD: safepassword
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SECRET_KEY: testsecret
      DEBUG: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations
        run: |
          cd backend
          python manage.py migrate

      - name: Run tests
        run: |
          cd backend
          python manage.py test

      - name: Run tests with coverage and upload to Codecov
        run: |
          cd backend
          coverage run manage.py test
          coverage report
          coverage xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: backend/coverage.xml
          flags: unittests
          name: codecov-coverage-report
          verbose: true
